/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Paquete;

import java.awt.BorderLayout;
import java.awt.FlowLayout;
import java.awt.GridLayout;
import javax.swing.JPanel;
import javax.swing.JScrollPane;

/**
 *
 * @author will
 */
public class Form extends javax.swing.JFrame {

    /**
     * Creates new form Form
     */
    public Form() {
        initComponents();
        this.setSize(1000, 805);
        holas hola1 = new holas();
        holas hola2 = new holas();
        holas hola3 = new holas();
        GridLayout grid = new GridLayout(20, 2);
        hola1.setSize(400, 300);
        grid.preferredLayoutSize(hola1);
        grid.setHgap(20);
        grid.setVgap(20);
        scp_Contenedor.setViewportView(new JPanel(grid));
        JPanel view = ((JPanel)scp_Contenedor.getViewport().getView());
        
        view.add(hola1);
        view.add(hola2);
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        view.add(new holas());
        
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        scp_Contenedor = new javax.swing.JScrollPane();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        scp_Contenedor.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_ALWAYS);
        scp_Contenedor.setVerticalScrollBarPolicy(javax.swing.ScrollPaneConstants.VERTICAL_SCROLLBAR_ALWAYS);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scp_Contenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(scp_Contenedor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane scp_Contenedor;
    // End of variables declaration//GEN-END:variables
}
