/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import GUI.Tools.NonEditableTableModel;
import Modelo.Productos.Producto;
import Modelo.Usuarios.Administrador;
import Modelo.Usuarios.Usuario;
import java.util.LinkedList;
import javax.swing.ListSelectionModel;

/**
 *
 * @author will
 */
public class ListaProductosGUI extends javax.swing.JDialog {

    private LinkedList<Producto> productosSeleccionados;
    private LinkedList<Producto> todosProductos;
    private Administrador administrador;
    
    private static final NonEditableTableModel productosTableModel = new NonEditableTableModel();
    private static final String[] productosHeaders = {"Producto", "Precio"};
    
    
        
    public ListaProductosGUI(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        tbl_Productos.setRowSelectionAllowed(true);
        tbl_Productos.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        productosSeleccionados = new LinkedList<>();
        todosProductos = new LinkedList<>();
        administrador = new Administrador();
    }
    
    public ListaProductosGUI(java.awt.Frame parent, boolean modal, Administrador pAdministrador, 
            LinkedList<Producto> pProductosSeleccionados) {
        
        super(parent, modal);
        initComponents();
        tbl_Productos.setRowSelectionAllowed(true);
        tbl_Productos.setSelectionMode(ListSelectionModel.MULTIPLE_INTERVAL_SELECTION);
        todosProductos = pAdministrador.getAllProductos();
        administrador = pAdministrador;
        productosSeleccionados = pProductosSeleccionados;
        refreshTblProductos();
        
    }
    
    private void refreshTblProductos()
    {
        
        int listSize = todosProductos.size();
        String[][] productosDatos = new String[listSize][2];
        for(int index = 0; index < listSize; index++)
        {
            Producto producto = todosProductos.get(index);
            productosDatos[index][0]= producto.getNombre();
            productosDatos[index][1]= Double.toString(producto.getPrecio());
            
        }
        
        productosTableModel.setDataVector(productosDatos, productosHeaders);
        tbl_Productos.setModel(productosTableModel);
        
        setSelectedProductos();
        
    }
    
    public void setSelectedProductos()
    {
        for(Producto producto : productosSeleccionados)
        {
            String nombreProducto = producto.getNombre();
            
            int rowCount = tbl_Productos.getRowCount();
            for(int indexRow = 0; indexRow < rowCount; indexRow++)
            {
                String nombreProductoTabla = (String)tbl_Productos.getValueAt(indexRow, 0);
                if(nombreProductoTabla.equals(nombreProducto))
                {
                    tbl_Productos.addRowSelectionInterval(indexRow, indexRow);
                }
            }
            
        }
    }
    
    public LinkedList<Producto> getProductosSeleccionados()
    {
        return productosSeleccionados;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_Productos = new javax.swing.JTable();
        btn_Salir = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        tbl_Productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbl_Productos);

        btn_Salir.setText("Salir");
        btn_Salir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_SalirActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Cantarell", 1, 12)); // NOI18N
        jLabel1.setText("Para Seleccionar multiples productos mantener precionada la tecla Ctrl al darle click a las filas");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btn_Salir)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 247, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(13, 13, 13)
                .addComponent(btn_Salir)
                .addContainerGap(15, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_SalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_SalirActionPerformed
        
        productosSeleccionados = new LinkedList<>();
        
        int indexRows[] = tbl_Productos.getSelectedRows();
        
        for(int indexRow : indexRows)
        {
            String nombreProducto = (String)tbl_Productos.getValueAt(indexRow, 0);
            Producto producto = administrador.getProductoPorNombre(nombreProducto);
            
            productosSeleccionados.add(producto);
            
        }
        
        this.dispose();
    }//GEN-LAST:event_btn_SalirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListaProductosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListaProductosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListaProductosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListaProductosGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListaProductosGUI dialog = new ListaProductosGUI(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btn_Salir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbl_Productos;
    // End of variables declaration//GEN-END:variables
}
